# Generated by Django 4.1.3 on 2022-12-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingrediente',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
