# Generated by Django 4.1.3 on 2022-11-26 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPago', models.IntegerField()),
                ('tipoPago', models.CharField(choices=[('TARJETA', 'tarjeta'), ('EFECTIVO', 'efectivo')], max_length=250)),
                ('estadoPago', models.CharField(choices=[('PENDIENTE', 'pendiente'), ('PAGADO', 'pagado')], max_length=250)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('mesa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.mesa')),
            ],
        ),
    ]
