# Generated by Django 4.1.3 on 2022-12-05 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        ('ingredients', '0002_ingrediente_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido_proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('ingrediente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingredients.ingrediente')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.proveedor')),
            ],
        ),
    ]
