# Generated by Django 4.1.3 on 2022-11-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('orders', '0002_orden_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.pago'),
        ),
    ]
